package main

const fileTemplate = `// Code generated by messenger-gen. DO NOT EDIT.

package {{.Spec.Package}}

import (
	"context"
{{- range .Spec.Imports}}
	{{.}}
{{- end}}
)

// {{.Spec.MessengerName}} is the generated message router.
type {{.Spec.MessengerName}} struct {
{{- range $handler := .Spec.Handlers}}
{{- if $.ReceivesMessages $handler.Name}}
	{{$handler.Name}} geninterfaces.{{$handler.Name | title}}Interface
{{- end}}
{{- end}}
}

// New{{.Spec.MessengerName}} creates a new messenger with dependencies
func New{{.Spec.MessengerName}}(
{{- range $i, $handler := .Spec.Handlers}}
{{- if $.ReceivesMessages $handler.Name}}
	{{$handler.Name}} geninterfaces.{{$handler.Name | title}}Interface,
{{- end}}
{{- end}}
) *{{.Spec.MessengerName}} {
	return &{{.Spec.MessengerName}}{
{{- range $handler := .Spec.Handlers}}
{{- if $.ReceivesMessages $handler.Name}}
		{{$handler.Name}}: {{$handler.Name}},
{{- end}}
{{- end}}
	}
}

{{range $handler := .Spec.Handlers}}
{{- $routes := $.RoutesForHandler $handler.Name}}
{{- if $routes}}
{{range $route := $routes}}
{{range $msg := $route.Messages}}
// Send{{$msg.Message | baseName}}From{{$handler.Name | title}} sends {{$msg.Message}} from {{$handler.Name}} to receivers
func (m *{{$.Spec.MessengerName}}) Send{{$msg.Message | baseName}}From{{$handler.Name | title}}(ctx context.Context, message {{$msg.Message}}) {{$msg.Response}} {
{{- range $receiver := $msg.Receivers}}
{{- if $.HasSendableMessages $receiver}}
	return m.{{$receiver}}.Handle{{$msg.Message | baseName}}(ctx, message, m)
{{- else}}
	return m.{{$receiver}}.Handle{{$msg.Message | baseName}}(ctx, message)
{{- end}}
{{- end}}
}
{{end}}
{{end}}
{{- end}}
{{end}}
`
