package main

const fileTemplate = `// Code generated by interface-gen. DO NOT EDIT.

package {{.Spec.Package}}

import (
	"context"
{{- range .Spec.Imports}}
	{{.}}
{{- end}}
)

{{range $handler := .Spec.Handlers}}
{{- $hasSendable := $.HasSendableMessages $handler.Name}}
{{- if $hasSendable}}
// {{$handler.Name | title}}Sendable defines the interface for messages that {{$handler.Name}} can send
type {{$handler.Name | title}}Sendable interface {
{{- range $route := $.RoutesForHandler $handler.Name}}
{{- range $msg := $route.Messages}}
	Send{{$msg.Message | baseName}}From{{$handler.Name | title}}(ctx context.Context, message {{$msg.Message}}) {{$msg.Response}}
{{- end}}
{{- end}}
}
{{- end}}

// {{$handler.Name | title}}Interface defines the interface for handling messages sent to {{$handler.Name}}
type {{$handler.Name | title}}Interface interface {
{{- range $route := $.RoutesReceivedBy $handler.Name}}
{{- range $msg := $route.Messages}}
{{- $isLast := $.IsLastReceiver $handler.Name $route.Source $msg.Message}}
{{- if $hasSendable}}
{{- if $isLast}}
	Handle{{$msg.Message | baseName}}(ctx context.Context, message {{$msg.Message}}, next {{$handler.Name | title}}Sendable) {{$msg.Response}}
{{- else}}
	Handle{{$msg.Message | baseName}}(ctx context.Context, message {{$msg.Message}}, next {{$handler.Name | title}}Sendable) error
{{- end}}
{{- else}}
{{- if $isLast}}
	Handle{{$msg.Message | baseName}}(ctx context.Context, message {{$msg.Message}}) {{$msg.Response}}
{{- else}}
	Handle{{$msg.Message | baseName}}(ctx context.Context, message {{$msg.Message}}) error
{{- end}}
{{- end}}
{{- end}}
{{- end}}
}

{{end}}
`
