# Message routing specification
# This file is shared between interface-gen and messenger-gen
# Defines the message routing graph for the configuration service

# Interface generation configuration
interfaces:
  package: interfaces
  imports:
    - 'commonpb "github.com/berendjan/golang-bazel-starter/proto/common/v1"'
    - 'configpb "github.com/berendjan/golang-bazel-starter/proto/configuration/v1"'

# Messenger generation configuration
messenger:
  package: messenger
  messenger_name: GrpcMessenger
  imports:
    - 'geninterfaces "github.com/berendjan/golang-bazel-starter/golang/generated/interfaces"'
    - 'commonpb "github.com/berendjan/golang-bazel-starter/proto/common/v1"'
    - 'configpb "github.com/berendjan/golang-bazel-starter/proto/configuration/v1"'

# Handler definitions
handlers:
  - name: accountRepository
    type: "configrepository.AccountDbRepository"
  - name: accountApi
    type: "configapi.ConfigurationApi"
  - name: middlewareOne
    type: "middleone.MiddleOne"
  - name: middlewareTwo
    type: "middletwo.MiddleTwo"

# Routes define message flow from sources to receivers
routes:
  - source: accountApi
    messages:

      - message: "*configpb.MiddleOneRequestProto"
        response: "(*configpb.AccountConfigurationProto, error)"
        receivers:
          - middlewareOne

      - message: "*configpb.AccountDeletionRequestProto"
        response: "(*commonpb.StatusResponseProto, error)"
        receivers:
          - middlewareTwo

      - message: "*configpb.ListAccountsRequestProto"
        response: "(*configpb.ListAccountsResponseProto, error)"
        receivers:
          - middlewareTwo

  - source: middlewareOne
    messages:

      - message: "*configpb.MiddleOneRequestProto"
        response: "(*configpb.AccountConfigurationProto, error)"
        receivers:
          - middlewareTwo
          - accountRepository

  - source: middlewareTwo
    messages:

      - message: "*configpb.AccountDeletionRequestProto"
        response: "(*commonpb.StatusResponseProto, error)"
        receivers:
          - accountRepository

      - message: "*configpb.ListAccountsRequestProto"
        response: "(*configpb.ListAccountsResponseProto, error)"
        receivers:
          - accountRepository
